language: node_js
node_js: 13

install:
  npm install --no-progress --quiet --silent

script:
  npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  target_branch: master
  repo: codice-lieve/codice-lieve.github.io
  on:
    branch: release
